name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross:v1.22
    steps:
      - run: |
          git config --global --add safe.directory /__w/go-guerrilla/go-guerrilla
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.22"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
